export const SAVE_USER = "SAVE_USER";
export const SAVE_USER_AAP = "SAVE_USER_AAP";
export const SAVE_PERSONAL_INFO = "SAVE_PERSONAL_INFO";
export const SAVE_ALL_CATEGORIES = "SAVE_ALL_CATEGORIES";
export const SAVE_PRODUCTS_BY_CATEGORY_ID = "SAVE_PRODUCTS_BY_CATEGORY_ID";
